import type { ProductSummary } from '@/src/types/api/products'

/**
 * SAMPLE DATA — placeholder catalog for the home while the products API does not exist.
 * Prices, installments, badges and stock flags are invented for layout purposes only.
 * TODO(api): replace with products.service.ts (featured products endpoint).
 */
export const SAMPLE_FEATURED_PRODUCTS: ProductSummary[] = [
  {
    id: 1,
    slug: 'epson-ecotank-l3250',
    name: 'Multifunción EcoTank L3250 Wi-Fi',
    brand: 'Epson',
    category: 'Impresoras para el hogar',
    highlight: 'Imprimí, escaneá y copiá desde el celular',
    imageUrl: '/images/epson/l3250.jpg',
    price: { amount: '389999.00', currency: 'ARS' },
    compareAtPrice: { amount: '429999.00', currency: 'ARS' },
    installments: 6,
    badge: 'BEST_SELLER',
    lowStock: false,
  },
  {
    id: 2,
    slug: 'epson-ecotank-l8180',
    name: 'Multifunción fotográfica EcoTank L8180 A3+',
    brand: 'Epson',
    category: 'Impresoras fotográficas',
    highlight: '6 colores para fotos de calidad profesional',
    imageUrl: '/images/epson/l8180.jpg',
    price: { amount: '1249999.00', currency: 'ARS' },
    compareAtPrice: null,
    installments: 12,
    badge: 'NEW',
    lowStock: true,
  },
  {
    id: 3,
    slug: 'epson-ecotank-l6490',
    name: 'Multifunción EcoTank L6490 para oficina',
    brand: 'Epson',
    category: 'Impresoras para oficina',
    highlight: 'Dúplex automático y alimentador de documentos',
    imageUrl: '/images/epson/l6490.png',
    price: { amount: '989999.00', currency: 'ARS' },
    compareAtPrice: { amount: '1099999.00', currency: 'ARS' },
    installments: 12,
    badge: 'OFFER',
    lowStock: false,
  },
  {
    id: 4,
    slug: 'epson-tinta-t664-cyan',
    name: 'Botella de tinta original T664 Cyan 70 ml',
    brand: 'Epson',
    category: 'Tintas originales',
    highlight: 'Rinde miles de páginas por botella',
    imageUrl: '/images/epson/ink-bottle.png',
    price: { amount: '18999.00', currency: 'ARS' },
    compareAtPrice: null,
    installments: null,
    badge: 'BEST_SELLER',
    lowStock: false,
  },
  {
    id: 5,
    slug: 'epson-perfection-v19-ii',
    name: 'Escáner fotográfico Perfection V19 II',
    brand: 'Epson',
    category: 'Escáneres',
    highlight: 'Digitalizá fotos y documentos en alta resolución',
    imageUrl: '/images/epson/v19ii.jpg',
    price: { amount: '219999.00', currency: 'ARS' },
    compareAtPrice: null,
    installments: 6,
    badge: null,
    lowStock: false,
  },
  {
    id: 6,
    slug: 'epson-workforce-es-400-ii',
    name: 'Escáner de documentos WorkForce ES-400 II',
    brand: 'Epson',
    category: 'Escáneres',
    highlight: 'Escaneo dúplex rápido para la oficina',
    imageUrl: '/images/epson/es-400ii.jpg',
    price: { amount: '799999.00', currency: 'ARS' },
    compareAtPrice: { amount: '869999.00', currency: 'ARS' },
    installments: 12,
    badge: 'OFFER',
    lowStock: true,
  },
  {
    id: 7,
    slug: 'epson-surecolor-t5170',
    name: 'Plotter SureColor T5170 de 36"',
    brand: 'Epson',
    category: 'Gran formato',
    highlight: 'Planos, CAD y cartelería con conexión Wi-Fi',
    imageUrl: '/images/epson/sc-t5170.jpg',
    price: { amount: '4899999.00', currency: 'ARS' },
    compareAtPrice: null,
    installments: 12,
    badge: null,
    lowStock: false,
  },
  {
    id: 8,
    slug: 'epson-workforce-pro-wf-c5890',
    name: 'Multifunción WorkForce Pro WF-C5890',
    brand: 'Epson',
    category: 'Impresoras para oficina',
    highlight: 'Alta velocidad y bajo costo por página',
    imageUrl: '/images/epson/wf-c5890.png',
    price: { amount: '1899999.00', currency: 'ARS' },
    compareAtPrice: null,
    installments: 12,
    badge: 'NEW',
    lowStock: false,
  },
]
